---
title: "2dim grid approx failed"
output: html_notebook
---


```{r}
mu.list <- seq(140, 160, length.out = 200)
sigma_list <- seq(4, 9, length.out = 200)

post <- expand.grid(mu = mu.list, sigma = sigma_list)
```
```{r}
class(post)
head(post)
```
```{r}
post$LL <- sapply(1:nrow(post),
                  function(i) sum( dnorm(
                    d$height,
                    mean = post$mu[i],
                    sd = post$sigma[i],
                    log = T
                  ))
                  )
post$prod <- post$LL + dnorm(post$mu, 178, 20, T) +
  dunif(post$sigma, 0, 50, T)

post$prob <- exp(post$prod-max(post$prod))
```

```{r}
sum(post$prob)
```


```{r}
contour_xyz(post$mu, post$sigma, post$prob)
image_xyz(post$mu, post$sigma, post$prob)
```
```{r}
nrow(post)
```
```{r}
post[20000:20005,]
```
```{r}
sample.rows <- sample(1:nrow(post), size= 1e4, replace = T, prob = post$prob)
sample.mu <- post$mu[sample.rows]
sample.sigma <- post$sigma[sample.rows]
```
```{r}
plot(sample.mu, sample.sigma, col=col.alpha(rangi2,0.1))
```


