---
title: "Ch4_tidy"
output: html_notebook
---

```{r setup}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	fig.height=3, 
	fig.width=7
)
library(tidyverse)
source("utilities.R")
```

```{r}
pos <- replicate(1000, runif(16,-1,1)) %>% 
  as.tibble() %>% 
  rbind(0,.) %>% 
  mutate(step=0:16) %>% 
  gather(key, value, -step) %>% 
  mutate(person = rep(1:1000, each = 17)) %>% 
  group_by(person) %>% 
  mutate(position=cumsum(value)) %>% 
  ungroup()
```

```{r}
pos %>% 
  ggplot(aes(x = step, y = position, group = person)) + 
  geom_line(aes(color=person<2, alpha = person<2)) + 
  geom_vline(xintercept = c(4,8,16), linetype = 2) + 
  scale_color_manual(values=c("skyblue4", "black")) + 
  scale_alpha_manual(values = c(0.2, 1)) + 
  scale_x_continuous("step number", breaks = c(0, 4, 8, 12, 16)) + 
  theme(legend.position = "none")
```
```{r}
pos_std <- pos %>% 
  filter(step == 16) %>% 
  summarise(sd = sd(position)) %>% as.numeric
```

```{r}
pos %>% 
  filter(step==16) %>% 
  ggplot(aes(x = position)) + 
  geom_density(color = "transparent", fill = "dodgerblue3", alpha=1/2) + 
  geom_line(data = tibble(position = seq(-7,7, by=0.1)),
            aes(x=position, y=dnorm(position,0, pos_std)), linetype=2)
```
```{r}
d <- tibble(
  w = 6,
  n = 9,
  p_grid = seq(0, 1, length.out = 1000)
) %>% 
  mutate(prior = dunif(p_grid, 0, 1),
         likelihood = dbinom(w, n, prob = p_grid)) %>%
  mutate(posterior = prior * likelihood) %>% 
  mutate(posterior = posterior / sum(posterior))
head(d)  
```
```{r}
d %>% 
  select(-w, -n) %>% 
  gather("k","v",-p_grid) %>% 
  mutate( k = factor(k, levels = c("prior", "likelihood", "posterior"))) %>% 
  ggplot(aes(x = p_grid, ymin = 0, ymax = v, fill = k)) + 
  geom_ribbon() +
  facet_wrap(~k, scales = "free") + 
  scale_y_continuous(NULL, breaks = NULL)
  
```
Load and unload rethinking, just for the data
```{r}
library(rethinking)
data("Howell1")
d <- Howell1
rm("Howell1")
detach(package:rethinking, unload = T)
library(brms)
```

```{r}
d %>% 
  glimpse()
```
```{r}
d2 <- d %>% 
  filter(age>=18)
```
this is prior predictive
```{r}
n <- 1e4

tibble(
  mu = rnorm(n, 178, 20),
  sigma = runif(n, 0, 50),
) %>% 
  mutate(x = rnorm(n, mu, sigma)) %>% 
  ggplot(aes(x=x)) +
  geom_density(fill="black", size = 0)+
  scale_y_continuous(NULL, breaks = NULL) + 
  labs(subtitle = expression(paste("Prior Predictive Distribution for ", italic(h[i]))), x=NULL
       ) + 
  theme(panel.grid = element_blank())
```
2 dim grid approximation
```{r}
n <- 200

theta_grid <- tibble(
  mu = seq(140, 160, length.out = n),
  sigma = seq(4, 9, length.out = n)
) %>% 
  expand(mu, sigma)

head(theta_grid)
```
```{r}
likelihood_function <- function(mu, sigma){
  dnorm(d2$height, mu, sigma, log = T) %>% 
    sum()
}
```
```{r}
theta_grid <- theta_grid %>% 
  mutate(log_likelihood = map2_dbl(mu, sigma, likelihood_function)) %>% 
  mutate(prior_mu = dnorm(mu, 178, 20),
         prior_sigma = dunif(sigma, 0, 50)) %>% 
  mutate(product = log_likelihood + prior_mu + prior_sigma) %>% 
  mutate(prob = exp(product - max(product)))
```
contour map
```{r}
theta_grid %>% 
  ggplot(aes(x = mu, y = sigma, z = prob)) + 
  geom_contour()+
  coord_cartesian(xlim = range(theta_grid$mu), ylim = range(theta_grid$sigma))
```

```{r}
theta_grid %>% 
  ggplot(aes(x=mu, y = sigma))+
  geom_raster(aes(fill = prob))
```
```{r}
post_samples <- 
  theta_grid %>% 
  sample_n(1e4, replace = T, weight = prob)
```
```{r}
post_samples %>% 
  ggplot(aes(x = mu, y = sigma)) + 
  geom_point(alpha=1/15)
```
```{r}
post_samples %>% 
  select(sigma, mu) %>% 
  gather() %>%  
  ggplot(aes(x = value)) + 
  geom_density()+
  facet_wrap(~key, scale = "free")
```
```{r}
library(tidybayes)
```

```{r}
post_samples %>% 
  select(mu, sigma) %>% 
  gather() %>% 
  group_by(key) %>% 
  mode_hdi(value)
```
# Model 4.1
```{r}
b4.1 <- brm(
  data = d2, family = gaussian,
  height ~ 1,
  prior = c(
    prior(normal(178, 20), class = Intercept),
    prior(uniform(0, 50), class = sigma)
  ),
  iter = 31000, warmup = 30000, chains =4, cores = 4
)
```
```{r}
b4.1_half_cauchy <- 
  brm(data = d2, family = gaussian,
      height ~ 1,
      prior = c(prior(normal(178, 20), class = Intercept),
                prior(cauchy(0, 1), class = sigma)),
      iter = 2000, warmup = 1000, chains = 4, cores = 4)
```
```{r}
plot(b4.1_half_cauchy)
```
```{r}
plot(b4.1)
```
```{r}
launch_shinystan(b4.1)
```
```{r}
b4.1$fit
```
```{r}
post <- posterior_samples(b4.1)
cov(post[1:2])
```
```{r}
posterior_summary(b4.1)
```

```{r}
d2 %>% 
  ggplot(aes(weight, height))+
  geom_point(shape=1, size=2)+
  theme_bw()
```
Model 4.3
```{r}
d2$weight.s <- scale(d2$weight)
```

```{r}
b4.3 <- brm(data=d2, family = gaussian,
            height ~ 1 + weight.s,
            prior = c(
              prior(normal(178, 20), class = Intercept),
              prior(lognormal(0,1), class = b),
              prior(cauchy(0,1), class = sigma)
            ),
            iter = 3000, warmup = 2000, chains = 4, cores = 4
            )
```

```{r}
b4.3prior <- brm(data=d2, family = gaussian,
            height ~ 1 + weight.s,
            prior = c(
              prior(normal(178, 20), class = Intercept),
              prior(lognormal(0,1), class = b),
              prior(cauchy(0,1), class = sigma)
            ),
            sample_prior = "only",
            iter = 3000, warmup = 2000, chains = 4, cores = 4
            )
```

```{r}
prior_predict <- posterior_samples(b4.3prior) 

d2 %>% 
  ggplot(aes(x=weight.s, y = height))+
  geom_point()+
  geom_abline(data = prior_predict[1:20,], aes(intercept = b_Intercept, slope = b_weight.s))
```
```{r}
post_predict <- posterior_samples(b4.3) 

d2 %>% 
  ggplot(aes(x=weight.s, y = height))+
  geom_point()+
  geom_abline(data = post_predict[1:20,], aes(intercept = b_Intercept, slope = b_weight.s))
```

```{r}
cor(post_predict[,1:3]) %>% round(2)
```



```{r}
get_prior(height ~ 1 + weight,data=d2)
```
```{r}
posterior_summary(b4.3)
```

# Link uncertainty
```{r}
specific_weight <- (50 - mean(d2$weight)) / sd(d2$weight)
post_predict %>% 
  transmute(mu_50 = b_Intercept + b_weight.s * specific_weight) -> mu_50
```
```{r}
mu_50_plot <- mu_50 %>% 
  ggplot(aes(x = mu_50))+
  geom_density(fill = "royalblue", color = "transparent")+
  theme_classic()
```

```{r}
mean_hdi(mu_50$mu_50,  .width =c(0.89,0.95))
```
```{r}
mu_50_plot + 
  stat_intervalh(aes(y=0), point_interval = mode_hdi, .width = 0.95)
```
```{r}
mu_s <- fitted(b4.3, summary = F)
```
```{r}
weight_seq <- (seq(25, 70, by =1) -mean(d2$weight))/ sd(d2$weight)
mu <- fitted(b4.3, summary = F, newdata = list(weight.s = weight_seq))
```
```{r}
mu <- mu %>% 
  as.tibble() %>% 
  mutate(Iter = 1:4000) %>% 
  select(Iter, everything())
mu %>% str()
```
```{r}
mu <- mu %>% 
  gather(key, value, V1:V46) %>% 
  mutate(key = str_extract(key, "\\d+") %>% as.integer()) %>% 
  rename(weight = key, height = value) %>% 
  mutate(weight = weight + 24) 

d2 %>% 
  ggplot(aes(weight, height))+
  geom_point() + 
  geom_point(data = mu %>% filter(Iter<101), alpha=0.1)
```

# regression line and its intervals
```{r}
mu_summary <- fitted(b4.3, newdata = list(weight.s = weight_seq)) %>% 
  as.tibble() %>% 
  bind_cols(list(weight = seq(25, 70, by = 1)))
```
```{r}
d2 %>% 
  ggplot(aes(weight))+
  geom_point(aes(y=height),shape = 1, color = "navyblue", alpha =1/3)+
  geom_ribbon(data = mu_summary, aes(ymax = Q97.5, ymin = Q2.5), fill = "grey70") +
  geom_line(data = mu_summary, aes(y=Estimate))
```
# With predictions
```{r}
weight_seq <- tibble(weight = seq(25, 70, by = 1)) %>% 
  mutate(weight.s = (weight - mean(d2$weight)) / sd(d2$weight))
```
```{r}
pred_height <- predict(b4.3, newdata = weight_seq)%>% as.tibble() %>% 
  bind_cols(weight_seq, .)
```
```{r}
pred_height %>% head
```


```{r}
weight_seq <- seq(25,70, by = 1) %>% scaler(d2$weight) %>% tibble(weight.s = .)
```

```{r}
ggplot()+
  geom_point(data = d2,
        aes(y = height, x= weight.s), shape=1)+
  plot_intervals(calc_intervals(weight_seq, b4.3))
```
```{r}
ggplot()+
  geom_point(data = d2,
        aes(y = height, x= weight.s), shape=1)+
  (calc_intervals(weight_seq, b4.3) %>% plot_intervals())
```
#4.5 polynomial regression with full dataset
```{r}
d %>% glimpse()
d <- d %>% 
  mutate(weight.s = scaler(weight, weight))
```
```{r}
b4.5 <- brm(data =d, family = gaussian,
            height ~ 1 + weight.s + I(weight.s ^ 2),
            prior = prior(normal(0, 20), class = "b")
            )
```

```{r}
get_prior(data =d, family = gaussian,
           height ~ 1 + weight.s + I(weight.s ^ 2),)
```
```{r}
stancode(b4.5)
```

```{r}
d %>% 
  ggplot()+
  geom_point(aes(weight.s, height))+
  plot_intervals(calc_intervals(model = b4.5, newdata = weight_seq))
```
```{r}
plot(b4.5)
```
```{r}
b4.5prior <- update(b4.5, sample_prior = "only")
```
```{r}
d %>% 
  ggplot()+
  geom_point(aes(weight.s, height))+
  plot_intervals(calc_intervals(model = b4.5prior, newdata = weight_seq))
```
```{r}
print(b4.5)
```
```{r}
print(b4.5prior)
```
```{r}
library(rethinking)
data(cherry_blossoms)
d <- cherry_blossoms
precis(d)
```
```{r}
rm(cherry_blossoms)
detach(package:rethinking, unload=T)
library(brms)
```
```{r}
d %>% 
  ggplot(aes(year, temp))+
  geom_line()
```

```{r}
d %>% 
  filter(complete.cases(temp)) -> d
  
```
```{r}
b4.6 <- brm(data = d, family = gaussian,
            temp~s(year)+1
            )
```
```{r}
d %>% 
  ggplot()+
  geom_point(aes(year, temp))+
  calc_intervals(d, b4.6) %>% plot_intervals
```


```{r}
d %>% glimpse()
```
```{r}
print(b4.6)
```
 
 