---
title: "Chapter11tools"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rethinking)
data(Kline)
d <- Kline
```

```{r}
d$P <- d$population %>% log %>% scale %>% as.numeric
d$contact_id <- ifelse(d$contact == "high", 2, 1)
```
```{r}
-10:100:200
```

```{r}

ggplot(data.frame(x = -10:100), aes(x)) + 
  stat_function(geom = "line", fun = dlnorm, args = list(3,1)) + 
  stat_function(geom = "line", fun = dlnorm, args = list(0,10), alpha = 1/3) +
  theme_minimal()
```
```{r}
hist(d$total_tools)
```
```{r}
a <- rnorm(1e4, 3, 0.5)
a <- exp(a)
mean(a)
```

```{r}
N <- 100
a <- rnorm(N, 3, 0.5)
b <- rnorm(N, 0, .2)
plot(NULL, xlim = c(-2,2), ylim = c(0, 100))
for (i in 1:N) curve(exp(a[i] + b[i] * x), add =T, col=col.alpha("black",.5))
```
```{r}
x_seq <-  seq(log(100), log(200000), length.out = 100)

lambda <- sapply(x_seq, function(x) exp(a + b * x))
plot(NULL, xlim = range(x_seq), ylim = c(0, 500))
for (i in 1:N) lines(x_seq, lambda[i,], col = col.alpha("black",0.5), lwd = 1.5)
```
```{r}
plot(NULL, xlim = exp(range(x_seq)), ylim = c(0, 500))
for (i in 1:N) lines(exp(x_seq), lambda[i,], col = col.alpha("black", 0.5), lwd = 1.5)
```

```{r}
dat <- with(d,
            list(
              T = total_tools,
              P = P,
              cid = as.integer(contact_id)
            )
            )
```

```{r}
m11.9 <- ulam(
  alist(
    T ~ dpois(lambda),
    log(lambda) <-  a[cid],
    a[cid] ~ dnorm(3, 0.5)
  ),
  data = dat, chains = 4, log_lik = TRUE
)
```
```{r message=FALSE, warning=FALSE, results=FALSE}
m11.10 <- ulam(
  alist(
    T ~ dpois(lambda),
    log(lambda) <-a[cid] + b[cid] * P,
    a[cid]~dnorm(3,.5),
    b[cid]~dnorm(0, 0.2)
  ),
  data = dat, chains = 4, log_lik = TRUE
)
```
```{r}
compare(m11.9, m11.10, func = LOO)
```

