---
title: "rugged"
author: "paul"
date: "2/3/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```
```{r}
data("rugged")
d <- rugged
```
```{r data-munging}
d$log_gdp <- log(d$rgdppc_2000)
dd <- d[ complete.cases(d$rgdppc_2000) , ]
dd$log_gdp_std <- dd$log_gdp / mean(dd$log_gdp)
dd$rugged_std <- dd$rugged / max(dd$rugged)
dd$cid <- ifelse( dd$cont_africa ==1, 1,2)
```

```{r}
m8.5 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu, sigma),
    mu <- a[cid] + b[cid]*(rugged_std - 0.215),
    a[cid] ~ dnorm(1,0.1),
    b[cid] ~ dnorm(0, 0.3),
    sigma ~ dexp(1)
  ), 
  data = dd
)
precis(m8.5, depth = 2)
```
```{r}
dat_slim <- list(
  log_gdp_std = dd$log_gdp_std,
  rugged_std = dd$rugged_std,
  cid = as.integer(dd$cid)
)
```
```{r}
str(dat_slim)
```

```{r}
m9.1 <- ulam(
  alist(
    log_gdp_std ~ dnorm(mu, sigma),
    mu <- a[cid] + b[cid]*(rugged_std-0.215),
    a[cid] ~ dnorm(1, 0.1),
    b[cid] ~ dnorm(0, 0.3),
    sigma ~ dexp(1)
    ),
  data = dat_slim,
  chains = 1
)
```

```{r}
precis(m9.1, depth = 2)
```
```{r}
# compare(m9.1, m8.5) # Check yourself, before you wreck yourself.
```

